apiVersion: v1
kind: Namespace
metadata:
  name: vidalcasino
---
apiVersion: v1
kind: Secret
metadata:
  name: casino-secrets
  namespace: vidalcasino
type: Opaque
data:
  DB_NAME: Y2FzaW5vX2Ri
  DB_USER: Y2FzaW5v
  DB_PASSWORD: Y2FzaW5v
  JWT_SECRET: Y2FtYmlhbWU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: vidalcasino
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: casino-secrets
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: casino-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: casino-secrets
              key: DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - casino
            - -d
            - casino_db
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - casino
            - -d
            - casino_db
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: vidalcasino
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-db
